/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Vector search result */
export interface SearchResult {
  /** SQLite row ID */
  id: number
  /** Similarity score (0-1, higher = more similar) */
  score: number
}
/** Index statistics */
export interface AnchorStats {
  /** Total indexed vectors */
  totalVectors: number
  /** Vector dimensions */
  dimensions: number
  /** Current capacity */
  capacity: number
  /** Memory usage in bytes */
  memoryUsage: number
}
/** SVD decomposition result (Phase 2) */
export interface SvdResult {
  /** Orthogonal basis vectors (k × dim, flattened) */
  u: Array<number>
  /** Singular values */
  s: Array<number>
  /** Number of retained components */
  k: number
  /** Vector dimension */
  dim: number
}
/** Gram-Schmidt orthogonal projection result (Phase 2) */
export interface ProjectionResult {
  /** Projection vector */
  projection: Array<number>
  /** Residual vector */
  residual: Array<number>
  /** Basis coefficients for each tag */
  basisCoefficients: Array<number>
}
/** EPA projection result (Phase 2) */
export interface EpaResult {
  /** Projection values on each principal component */
  projections: Array<number>
  /** Energy distribution probabilities */
  probabilities: Array<number>
  /** Projection entropy */
  entropy: number
  /** Total energy */
  totalEnergy: number
}
/** Tag cooccurrence expansion result */
export interface TagExpansionResult {
  /** Expanded tag ID */
  tagId: number
  /** Cooccurrence weight */
  weight: number
  /** Which seed tag caused this expansion */
  source: number
}
/** AnchorIndex - High-performance vector index with HNSW + SQLite */
export declare class AnchorIndex {
  /** Create a new empty index */
  constructor(dim: number, capacity: number)
  /** Load an existing index from disk */
  static load(indexPath: string, dim: number, capacity: number): AnchorIndex
  /** Save index to disk (atomic write) */
  save(indexPath: string): void
  /** Add a single vector */
  add(id: number, vector: Buffer): void
  /** Add vectors in batch */
  addBatch(ids: Array<number>, vectors: Buffer): void
  /** Search for nearest neighbors */
  search(query: Buffer, k: number): Array<SearchResult>
  /** Remove a vector by id */
  remove(id: number): void
  /** Get index statistics */
  stats(): AnchorStats
  /** Initialize SQLite database schema at the given path */
  static initDatabase(dbPath: string): void
  /**
   * Compute SVD on a matrix of N row vectors.
   * `vectors`: N×dim flattened Buffer (f32), `n`: row count, `max_k`: max components
   */
  computeSvd(vectors: Buffer, n: number, maxK: number): SvdResult
  /**
   * Gram-Schmidt orthogonal projection of a vector onto tag basis vectors.
   * `vector`: dim-length Buffer, `tags`: n_tags×dim flattened Buffer, `n_tags`: tag count
   */
  computeOrthogonalProjection(vector: Buffer, tags: Buffer, nTags: number): ProjectionResult
  /**
   * EPA: project vector onto SVD basis, analyze energy distribution.
   * `vector`: dim-length, `basis`: k×dim, `mean`: dim-length (centering), `k`: component count
   */
  project(vector: Buffer, basis: Buffer, mean: Buffer, k: number): EpaResult
  /**
   * Expand seed tags by 1-hop cooccurrence.
   * Returns Vec<{tagId, weight, source}> sorted by weight descending.
   */
  expandTags(seedIds: Array<number>, coocTagA: Array<number>, coocTagB: Array<number>, coocWeights: Array<number>, topN: number, minWeight: number): Array<TagExpansionResult>
  /** Compute cosine similarity between two vectors (f32 Buffers) */
  cosineSimilarity(a: Buffer, b: Buffer): number
}
